---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-chaos-gushchin-dev-v1alpha1-chaosexperiment
  failurePolicy: Fail
  name: vchaosexperiment.kb.io
  rules:
  - apiGroups:
    - chaos.gushchin.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chaosexperiments
  sideEffects: None
