# This rule is not used by the project k8s-chaos itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to chaos.gushchin.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-chaos
    app.kubernetes.io/managed-by: kustomize
  name: chaosexperiment-viewer-role
rules:
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments/status
  verbs:
  - get
