# This rule is not used by the project k8s-chaos itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the chaos.gushchin.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-chaos
    app.kubernetes.io/managed-by: kustomize
  name: chaosexperiment-editor-role
rules:
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments/status
  verbs:
  - get
