---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments/finalizers
  verbs:
  - update
- apiGroups:
  - chaos.gushchin.dev
  resources:
  - chaosexperiments/status
  verbs:
  - get
  - patch
  - update
