# Minimal Grafana deployment for lab purposes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards-provisioning
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboards-provisioning
        configMap:
          name: grafana-dashboards-provisioning
      - name: dashboards
        configMap:
          name: grafana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      isDefault: true
      access: proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provisioning
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: 'k8s-chaos'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  k8s-chaos-overview.json: |
    {
      "title": "K8s Chaos - Overview",
      "uid": "k8s-chaos-overview",
      "tags": ["k8s-chaos"],
      "timezone": "browser",
      "panels": [
        {
          "title": "Total Experiments",
          "type": "stat",
          "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0},
          "targets": [{"expr": "sum(chaos_experiments_total)", "refId": "A"}]
        },
        {
          "title": "Success Rate",
          "type": "gauge",
          "gridPos": {"h": 4, "w": 6, "x": 6, "y": 0},
          "targets": [{"expr": "sum(chaos_experiments_total{status=\"success\"}) / sum(chaos_experiments_total) * 100", "refId": "A"}],
          "fieldConfig": {"defaults": {"unit": "percent", "max": 100, "min": 0}}
        },
        {
          "title": "Active Experiments",
          "type": "stat",
          "gridPos": {"h": 4, "w": 6, "x": 12, "y": 0},
          "targets": [{"expr": "chaos_experiments_active", "refId": "A"}]
        },
        {
          "title": "Experiments by Action",
          "type": "piechart",
          "gridPos": {"h": 8, "w": 12, "x": 0, "y": 4},
          "targets": [{"expr": "sum by (action) (chaos_experiments_total)", "refId": "A", "legendFormat": "{{action}}"}]
        },
        {
          "title": "Experiment Rate",
          "type": "timeseries",
          "gridPos": {"h": 8, "w": 12, "x": 12, "y": 4},
          "targets": [{"expr": "sum(rate(chaos_experiments_total[5m])) by (action)", "refId": "A", "legendFormat": "{{action}}"}]
        }
      ],
      "schemaVersion": 38,
      "version": 1
    }