apiVersion: chaos.gushchin.dev/v1alpha1
kind: ChaosExperiment
metadata:
  labels:
    app.kubernetes.io/name: k8s-chaos
    app.kubernetes.io/managed-by: kustomize
  name: chaosexperiment-sample
spec:
  # TODO(user): Add fields here
