apiVersion: chaos.gushchin.dev/v1alpha1
kind: ChaosExperiment
metadata:
  labels:
    app.kubernetes.io/name: k8s-chaos
    app.kubernetes.io/managed-by: kustomize
  name: chaosexperiment-network-delay
  namespace: staging
spec:
  # Add network latency to pods
  action: "pod-delay"

  # Target namespace
  namespace: "staging"

  # Target API service pods
  selector:
    app: api-service
    tier: backend

  # Add delay to 2 pods to test resilience
  count: 2

  # Duration of network delay to add (in milliseconds internally)
  # Format: combinations of numbers with units (s=seconds, m=minutes, h=hours)
  # Examples: "30s", "5m", "1h30m"
  # Note: Controller converts to milliseconds (30s = 30000ms delay)
  duration: "30s"

  # Optional: ExperimentDuration defines how long the experiment runs before auto-stopping
  # Uncomment to enable duration-based lifecycle (auto-stop after 15 minutes)
  # experimentDuration: "15m"