# Critical namespace - entirely excluded from chaos
apiVersion: v1
kind: Namespace
metadata:
  name: critical-ns
  labels:
    environment: critical
  annotations:
    chaos.gushchin.dev/exclude: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-critical
  namespace: critical-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi