# Simulated Microservices Environment
# Using nginx to simulate different service tiers

---
# Frontend Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chaos-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        zone: zone-a
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chaos-lab
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

---
# API Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: chaos-lab
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: api
        zone: zone-b
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: chaos-lab
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80

---
# Database Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: chaos-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: database
        zone: zone-c
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: chaos-lab
spec:
  selector:
    app: database
  ports:
  - port: 80
    targetPort: 80

---
# Cache Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: chaos-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
        tier: cache
        zone: zone-a
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: chaos-lab
spec:
  selector:
    app: cache
  ports:
  - port: 80
    targetPort: 80